### ISSUE TITLE
TTS-CN: SYN6288测试文本

### ISSUE THREAD

**Issue by whc2001** [l-O-O-l/TTS-action#51]
多音字识别。着： 他好像不着急，一边看着电视，一边打着电话：“高，这一着真高，我们马上就着手准备。”。重： 当前工作的重中之重是要在重重困难中保证重庆市的重点工程的顺利进行，坚决拒绝重复建设。折： 本店清仓折本出售，优惠多多。双休日穿着类商品五到八折，会员可再享受九五折优惠。变音识别。三声： 请你给我打桶洗脚水。轻声： 我们家奶奶和哥哥的耳朵最灵了。

**Comment by whc2001** [comment]
```
Traceback (most recent call last):
  File "../../mtts/synthesize2.py", line 95, in <module>
    name, tokens = text_processor(line)
  File "/work/mandarin-tts/mtts/text/text_processor.py", line 44, in __call__
    return self._process(input)
  File "/work/mandarin-tts/mtts/text/text_processor.py", line [27](https://github.com/l-O-O-l/TTS-action/runs/5257781726?check_suite_focus=true#step:6:27), in _process
    raise ValueError('Input text and emb_tokensizers are different, {segments}')
ValueError: Input text and emb_tokensizers are different, {segments}
```
